### ISSUE TITLE
Recommended upstream alignment

### ISSUE THREAD

**Issue by holtjma** [Illumina/Cyrius#1]
I was tinkering with the software, mainly to see ease-of-use and ran into an issue with regards to upstream processing.  I have two alignment processes that are almost identical (sentieon align, dedup, BQSR) except one performs postalt correction and the other does not.  When I run on three NA12878 replicates I get the following results:
No-postalt:
```
Sample	Genotype
SL362490	*3/*4+*68
SL362491	*3/*4+*68
SL362492	*3/*4+*68
```
Postalt+:
```
Sample	Genotype
SL362490	None
SL362491	None
SL362492	None
```
The difference is obvious, which leads to the question of what's recommended for upstream alignment?  Will performing postalt processing always lead to `None` or is there some workaround that will fix that?

**Comment by xiao-chen-xc** [comment]
Hi @holtjma 

I tried postalt and it changes the majority of reads in CYP2D6 from a good MapQ to a MapQ of 0, due to equally-good alignments to some ALT contigs. This causes problem to Cyrius as it uses those good reads to call variants. I think the most straightforward solution would be to use the bams before postalt to run Cyrius. If that's not feasible, we can think of some workaround to work with postalt-processed bams. 

Thanks,
Xiao

**Comment by holtjma** [comment]
Thanks for the response, I suspected it was something along those lines.  Post-alt processing seems to be a mixed bag of good and bad, so I'm not _too_ surprised that it would cause an issue in this particular context.

As for the workaround, yea that probably isn't feasible for a long-term solution.  Post-alt is usually done on read-sorted BAMs (and then sorted afterwards), and I think Cyrius requires position sorted based on the speed.  It's obviously doable, just redundant in some aspects.  I'll continue testing with some BAMs processed without post-alt for now.

On the plus side, the tool seemed to work right out of the box on non-postalt and was quite fast!

**Comment by xiao-chen-xc** [comment]
Glad to know it's working well for you. Feel free to reach out to me if you run into any other problem.
