### ISSUE TITLE
Question about "None" phenotype

### ISSUE THREAD

**Issue by joseph-yclam** [Illumina/Cyrius#25]
Hello,

I wanted to ask if Cyrius yields "None" for the phenotype, is it the same as declaring "Indeterminate" for the gene's metabolizer status? I wanted to test concordance with another program! 

Thank you.

**Comment by xiao-chen-xc** [comment]
Hi @joseph-yclam "None" means a no-call, that is, Cyrius is not able to give a definite genotype call.

**Comment by joseph-yclam** [comment]
@xiao-chen-xc I see, thank you so much! May I ask if there is any reason that might be the case? Would it perhaps have something to do with the particular combination of alleles of my sample data or it being whole genome-sequenced?

**Comment by xiao-chen-xc** [comment]
There could be multiple possible reasons for a no-call. Are you getting no-calls in a lot of samples or just one sample? If it's just one or two samples, it could be due to low sequencing depth (we recommend >30X WGS), or it could be due to some noise in the locus, a novel star allele or a complicated structural variant. If you share with me the .json output, I can take a look and tell you why the no-call was made. 

If you are getting no-calls in lots of samples, it's either low depth or possibly related to the pipeline that generates the BAM files. Two possible things to check are, as listed in the README:
-The depth of the CYP2D6/CYP2D7 region is much lower than the rest of the genome, most likely because reads are aligned to alternative contigs. If your reference genome includes alternative contigs, we suggest alt-aware alignment so that alignments to the primary assembly take precedence over alternative contigs.
-The majority of reads in CYP2D6/CYP2D7 region have a mapping quality of zero. This is probably due to some post-processing tools like bwa-postalt that modifies the mapQ in the BAM. We recommend using the BAM file before such post-processing steps as input to Cyrius.

**Comment by joseph-yclam** [comment]
@xiao-chen-xc I see, thank you so much! I have just sent an email containing the .json output!

**Comment by xiao-chen-xc** [comment]
Question solved by email.
